[phases.setup]
nixPkgs = [
    "stdenv.cc.cc.lib",
    "libGL",
    "libGLU",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender",
    "xorg.libXinerama",
    "xorg.libXcursor",
    "xorg.libXrandr",
    "xorg.libXi",
    "xorg.libXxf86vm"
]

aptPkgs = [
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender1",
    "libgl1"
]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn App:app --bind 0.0.0.0:$PORT"