[phases.setup]
apt_pkgs = [
  "libgl1",              # OpenGL library
  "libglib2.0-0",        # GLib for graphics
  "libgl1-mesa-glx",     # Mesa OpenGL implementation
  "libglib2.0-bin",      # Extra GLib utilities
  "libxrender1",         # For rendering
  "libxext6",            # X11 extension library
  "libsm6",              # Session management library
  "libx11-6"             # Core X11 client-side library
]
